'use strict';
const api=window.brain;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stage=document.getElementById('stage');
const state={tab:'notes',view:'list',id:null,query:'',notes:[],accounts:[],settings:null,vault:{exists:false,unlocked:false},version:'',save:'saved'};
const pending=new Map();
const secretWrites=new Set();
let saveTimer,draining=null,toastTimer,lastDeleted=null,activityAt=0,closing=false;
const list=()=>state.tab==='notes'?state.notes:state.accounts;
const current=()=>list().find(n=>n.id===state.id);
const sortItems=items=>[...items].sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.updatedAt.localeCompare(a.updatedAt));
const dateLabel=date=>{const d=new Date(date),now=new Date();if(d.toDateString()===now.toDateString())return '今天';const yesterday=new Date();yesterday.setDate(now.getDate()-1);if(d.toDateString()===yesterday.toDateString())return '昨天';return `${d.getMonth()+1}月${d.getDate()}日`;};
function notify(message,undo=false){clearTimeout(toastTimer);const element=document.getElementById('toast');element.innerHTML=`<span>${esc(message)}</span>${undo?'<button id="undo-delete">撤销</button>':''}`;element.hidden=false;if(undo)document.getElementById('undo-delete').onclick=()=>undoDelete().catch(showError);toastTimer=setTimeout(()=>{element.hidden=true;lastDeleted=null;},undo?10000:4500);}
function showError(error){notify(error.message||String(error));}
function saveStatus(){const element=document.querySelector('.save-status');if(!element||state.view!=='edit')return;element.classList.toggle('failed',state.save==='error');element.innerHTML=state.save==='saved'?`${icon('check')}已保存到本机`:state.save==='saving'?'正在保存…':'保存失败 <button data-action="retry">重试</button>';element.querySelector('button')?.addEventListener('click',()=>flush().catch(showError));}
function queueSave(item,secret){state.save='saving';saveStatus();if(secret){pending.delete('v:'+item.id);const snapshot=structuredClone(item);const write=api.saveAccount(snapshot);secretWrites.add(write);write.then(()=>{if(secretWrites.size===1&&!pending.size){state.save='saved';saveStatus();}}).catch(error=>{const latest=state.accounts.find(n=>n.id===snapshot.id);if(state.vault.unlocked&&latest)pending.set('v:'+snapshot.id,{item:structuredClone(latest),secret:true});state.save='error';saveStatus();showError(error);}).finally(()=>secretWrites.delete(write));return;}pending.set('n:'+item.id,{item:structuredClone(item),secret:false});clearTimeout(saveTimer);saveTimer=setTimeout(()=>flush().catch(showError),300);}
function flush(){clearTimeout(saveTimer);if(draining)return draining;if(!pending.size&&!secretWrites.size)return Promise.resolve();
 draining=(async()=>{try{while(secretWrites.size)await Promise.all([...secretWrites]);while(pending.size){const [key,job]=pending.entries().next().value;pending.delete(key);try{await (job.secret?api.saveAccount(job.item):api.saveNote(job.item));}catch(error){if(!pending.has(key)&&(!job.secret||state.vault.unlocked))pending.set(key,job);throw error;}}state.save='saved';saveStatus();}catch(error){state.save='error';saveStatus();throw error;}finally{draining=null;}})();
 return draining;
}
async function flushAll(){await flush();await window.appearance?.flush();}
function closeDialogs(){for(const dialog of document.querySelectorAll('dialog[open]'))dialog.close();document.body.classList.remove('appearance-open');document.getElementById('password-dialog').replaceChildren();}
async function hideWindow(quit=false){if(closing)return;closing=true;try{await flushAll();closeDialogs();await (quit?api.quit():api.hide());}catch(error){await api.cancelHide();showError(error);}finally{closing=false;}}
window.appHide=()=>hideWindow();
function paletteIcon(){return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3a9 9 0 1 0 0 18h1a2 2 0 0 0 1.4-3.4 1 1 0 0 1 .7-1.7H17a4 4 0 0 0 4-4A9 9 0 0 0 12 3Z"/><circle cx="7.5" cy="10" r=".7"/><circle cx="10" cy="6.8" r=".7"/><circle cx="14" cy="6.8" r=".7"/><circle cx="17" cy="10" r=".7"/></svg>';}
function header(){return `<header class="app-header"><div class="identity"><div class="mark">${icon('book')}</div><div><h1 class="wordmark">超强大脑</h1><p class="tagline">随手记，随时找。</p></div></div><div class="header-actions"><button class="icon-btn" data-appearance-open title="外观设置" aria-label="外观设置">${paletteIcon()}</button><button class="icon-btn" data-action="lock" title="锁定密码库" aria-label="锁定密码库">${icon(state.vault.unlocked?'unlock':'lock')}</button><button class="icon-btn" data-action="hide" title="收起到托盘" aria-label="收起到托盘">${icon('x')}</button></div></header>`;}
function tabs(){return `<div class="tabs" role="tablist" aria-label="内容类型"><button class="tab" role="tab" id="notes-tab" aria-controls="content-panel" aria-selected="${state.tab==='notes'}" tabindex="${state.tab==='notes'?0:-1}" data-tab="notes">${icon('note')}备忘录 <span class="count">${state.notes.length}</span></button><button class="tab" role="tab" id="vault-tab" aria-controls="content-panel" aria-selected="${state.tab==='vault'}" tabindex="${state.tab==='vault'?0:-1}" data-tab="vault">${icon('key')}账号密码 ${icon('lock')}</button></div>`;}
function footer(){return `<footer class="app-footer"><span class="save-status">${state.tab==='vault'&&!state.vault.unlocked?'密码库已锁定':`${list().length} 条${state.tab==='notes'?'备忘录':'账号记录'}`}</span><button data-action="settings">设置</button><span class="footer-hint"><kbd>${esc(state.view==='edit'?'Esc':state.settings.shortcut)}</kbd>${state.view==='edit'?'返回':'收起'}</span></footer>`;}
function render(){
 stage.innerHTML=`<section class="panel" aria-label="超强大脑">${header()}${state.view==='list'?tabs():''}<div class="main-view" id="content-panel" ${state.view==='list'?`role="tabpanel" aria-labelledby="${state.tab}-tab"`:''}>${state.view==='edit'?editor():listView()}</div>${footer()}</section>`;
 bind();
 if(state.view==='edit'){bindEditor();saveStatus();}
 else if(state.tab==='notes'||state.vault.unlocked){renderRows();document.getElementById('search').oninput=event=>{state.query=event.target.value;renderRows();};}
 else bindUnlock();
}
function listView(){
 if(state.tab==='vault'&&!state.vault.unlocked){const setup=!state.vault.exists;return `<section class="lock-view"><div class="lock-art">${icon('lock')}</div><h2>${setup?'为密码库设置主密码':'解锁你的密码库'}</h2><p>${setup?'账号、密码和私密备注会加密保存。':'普通备忘录可以继续使用。'}</p><form class="unlock-form" id="unlock-form"><div><label for="master-password">${setup?'设置主密码':'主密码'}</label><input id="master-password" type="password" autocomplete="${setup?'new-password':'current-password'}" required maxlength="1024" ${setup?'minlength="12"':''}></div>${setup?'<div><label for="confirm-password">再次输入主密码</label><input id="confirm-password" type="password" autocomplete="new-password" required maxlength="1024"></div><p class="recovery-note">至少 12 个字符，可用较长的中文短句。主密码无法找回，请另行妥善保管。</p><label class="checkbox-line"><input id="master-acknowledge" type="checkbox" required><span>我已了解：忘记主密码将无法解密已有密码。</span></label>':''}<p class="form-error" id="unlock-error" role="alert"></p><button class="primary" type="submit">${icon('unlock')}${setup?'创建密码库':'解锁'}</button></form><span class="lock-detail">仅在本机保存 · 收起窗口后锁定</span></section>`;}
 return `${state.tab==='vault'?`<div class="vault-strip"><span>${icon('shield')}已解锁 · 本地加密保存</span><button class="text-btn" data-action="lock">立即锁定</button></div>`:''}<div class="toolbar"><label class="search-wrap" for="search">${icon('search')}<span class="sr">${state.tab==='notes'?'搜索备忘录':'搜索账号名称或用户名'}</span><input id="search" type="search" placeholder="${state.tab==='notes'?'搜索备忘录…':'搜索账号或用户名…'}" value="${esc(state.query)}" autocomplete="off"></label><button class="primary" data-action="new">${icon('plus')}新建</button></div><div id="list" class="list"></div>`;
}
function renderRows(){const element=document.getElementById('list');if(!element)return;const query=state.query.trim().toLocaleLowerCase();const filtered=sortItems(list()).filter(item=>(item.title+' '+(state.tab==='notes'?item.body:item.username)).toLocaleLowerCase().includes(query));let html='';const groups=query?[['搜索结果',filtered]]:[['置顶',filtered.filter(n=>n.pinned)],['最近',filtered.filter(n=>!n.pinned)]];
 for(const [name,rows]of groups){if(!rows.length)continue;html+=`<div class="group-label">${name==='置顶'?icon('pin'):''}${name}</div>`;for(const item of rows)html+=`<button class="item ${item.pinned&&!query?'pinned':''}" data-open="${esc(item.id)}" aria-label="打开 ${esc(item.title||'未命名')}">${state.tab==='vault'?`<span class="vault-avatar">${esc((item.title||'账').slice(0,1))}</span>`:''}<span class="item-content"><span class="item-title-line"><span class="item-title">${esc(item.title||'未命名')}</span><span class="item-time">${dateLabel(item.updatedAt)}</span></span><span class="item-preview">${esc(state.tab==='notes'?(item.body.split('\n').find(Boolean)||'写一点什么…'):(item.username||'暂无用户名'))}</span></span>${icon('arrow','chevron')}</button>`;}
 element.innerHTML=html||`<div class="empty">${icon(query?'search':state.tab==='notes'?'note':'key')}<h2>${query?'没有找到相关内容':state.tab==='notes'?'把重要的事，先记下来。':'添加你的第一个账号'}</h2><p>${query?'换个关键词试试。':state.tab==='notes'?'一个想法，一件小事，都可以放在这里。':'名称、账号和密码，之后随时查找。'}</p>${query?'':'<button class="primary" data-action="new">新建一条</button>'}</div>`;
 element.querySelectorAll('[data-open]').forEach(button=>button.onclick=()=>openItem(button.dataset.open).catch(showError));element.querySelector('[data-action="new"]')?.addEventListener('click',()=>action('new').catch(showError));
}
function editor(){const item=current();if(!item)return '';return `<div class="editor-bar"><button class="back-btn" data-action="back">${icon('back')}${state.tab==='notes'?'全部备忘录':'全部账号'}</button><div class="editor-tools"><button class="icon-btn" data-action="pin" aria-label="${item.pinned?'取消置顶':'置顶'}" title="${item.pinned?'取消置顶':'置顶'}" aria-pressed="${item.pinned}">${icon('pin')}</button><button class="icon-btn delete-btn" data-action="delete" aria-label="删除这一条" title="删除这一条">${icon('trash')}</button></div></div><div class="editor-area"><label class="sr" for="edit-title">标题</label><input id="edit-title" class="title-input" value="${esc(item.title)}" placeholder="给这条记录起个名字" autocomplete="off" maxlength="120"><div class="editor-meta">${item.pinned?'<span class="small-tag">已置顶</span>':''}<span>${state.tab==='vault'?'加密保存':'本地备忘录'}</span><span>·</span><span>${dateLabel(item.updatedAt)}修改</span></div>${state.tab==='notes'?`<label class="sr" for="edit-body">备忘录正文</label><textarea id="edit-body" class="note-body" placeholder="想到什么，就写下来…" maxlength="100000" spellcheck="false">${esc(item.body)}</textarea>`:`<div class="field"><label for="edit-username">账号 / 用户名</label><div class="field-line"><input id="edit-username" value="${esc(item.username)}" autocomplete="off" maxlength="2048"><button class="icon-btn" data-copy="username" aria-label="复制账号" title="复制账号">${icon('copy')}</button></div></div><div class="field"><label for="edit-password">密码</label><div class="field-line"><input class="password-input" id="edit-password" type="password" value="${esc(item.password)}" autocomplete="off" maxlength="4096"><button class="icon-btn" data-action="reveal" aria-label="显示密码" title="显示密码">${icon('eye')}</button><button class="icon-btn" data-copy="password" aria-label="复制密码" title="复制密码">${icon('copy')}</button></div><div class="password-extra"><button class="text-btn" data-action="generate">生成随机密码</button></div></div><div class="field"><label for="edit-url">网站（选填）</label><div class="field-line"><input id="edit-url" value="${esc(item.url)}" placeholder="https://example.com" autocomplete="off" maxlength="2048"></div></div><div class="field"><label for="edit-body">备注</label><textarea id="edit-body" maxlength="100000" placeholder="补充一点说明…">${esc(item.body)}</textarea></div>`}</div>`;}
function bind(){stage.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>action(button.dataset.action).catch(showError));stage.querySelectorAll('[data-tab]').forEach(button=>{button.onclick=()=>switchTab(button.dataset.tab).catch(showError);button.onkeydown=async event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const tab=event.key==='Home'?'notes':event.key==='End'?'vault':state.tab==='notes'?'vault':'notes';try{await switchTab(tab);document.getElementById(tab+'-tab')?.focus();}catch(error){showError(error);}}};});stage.querySelectorAll('[data-copy]').forEach(button=>button.onclick=async()=>{try{await flush();await api.copyAccount(state.id,button.dataset.copy);notify('已复制，30 秒后清除本次复制内容');}catch(error){showError(error);}});}
function bindEditor(){for(const field of ['title','body','username','password','url']){const input=document.getElementById('edit-'+field);if(!input)continue;input.oninput=()=>{const item=current();if(!item)return;item[field]=input.value;item.updatedAt=new Date().toISOString();queueSave(item,state.tab==='vault');};}}
function bindUnlock(){const form=document.getElementById('unlock-form');form.onsubmit=async event=>{event.preventDefault();const setup=!state.vault.exists;const input=document.getElementById('master-password');const password=input.value;const error=document.getElementById('unlock-error');if(setup&&password!==document.getElementById('confirm-password').value){error.textContent='两次输入的主密码不一致';return;}const button=form.querySelector('button');button.disabled=true;button.textContent=setup?'正在创建…':'正在解锁…';error.textContent='';try{const accounts=await (setup?api.setupVault(password):api.unlockVault(password));input.value='';form.reset();state.accounts=accounts;state.vault={exists:true,unlocked:true};state.view='list';state.query='';render();document.getElementById('search')?.focus();}catch(e){if(form.isConnected){error.textContent=e.message;input.value='';input.focus();button.disabled=false;button.textContent=setup?'创建密码库':'解锁';}}};}
async function openItem(id){await flush();state.id=id;state.view='edit';render();stage.querySelector('[data-action="back"]')?.focus();}
async function switchTab(tab){await flush();state.tab=tab;state.view='list';state.query='';state.id=null;render();}
async function action(name){
 if(name==='hide')return hideWindow();
 if(name==='settings'){await flushAll();openSettings();return;}
 if(name==='retry')return flush();
 if(name==='back'){await flush();const id=state.id;state.view='list';state.id=null;render();Array.from(stage.querySelectorAll('[data-open]')).find(b=>b.dataset.open===id)?.focus();return;}
 if(name==='lock'){await flush();await api.lockVault();state.tab='vault';state.view='list';state.query='';render();return;}
 if(name==='new'){await flush();const now=new Date().toISOString();const item={id:crypto.randomUUID(),title:'',body:'',pinned:false,createdAt:now,updatedAt:now,...(state.tab==='vault'?{username:'',password:'',url:''}:{})};list().unshift(item);queueSave(item,state.tab==='vault');state.id=item.id;state.view='edit';render();document.getElementById('edit-title').focus();return;}
 if(name==='pin'){const item=current();item.pinned=!item.pinned;item.updatedAt=new Date().toISOString();queueSave(item,state.tab==='vault');await flush();render();stage.querySelector('[data-action="pin"]').focus();return;}
 if(name==='delete'){await flush();const secret=state.tab==='vault';const item=current();await(secret?api.deleteAccount(item.id):api.deleteNote(item.id));lastDeleted={item:structuredClone(item),secret};const array=list();array.splice(array.findIndex(n=>n.id===item.id),1);state.view='list';state.id=null;state.query='';render();notify('已删除这条记录',true);return;}
 if(name==='reveal'){const input=document.getElementById('edit-password');const show=input.type==='password';input.type=show?'text':'password';const button=stage.querySelector('[data-action="reveal"]');button.innerHTML=icon(show?'eyeoff':'eye');button.setAttribute('aria-label',show?'隐藏密码':'显示密码');button.title=show?'隐藏密码':'显示密码';return;}
 if(name==='generate'){const value=await api.generatePassword();const input=document.getElementById('edit-password');if(!input)return;input.value=value;input.dispatchEvent(new Event('input'));notify('已生成 24 位随机密码');}
}
async function undoDelete(){if(!lastDeleted)return;const {item,secret}=lastDeleted;if(secret&&!state.vault.unlocked)throw Error('请先解锁密码库');await(secret?api.saveAccount(item):api.saveNote(item));(secret?state.accounts:state.notes).unshift(item);lastDeleted=null;state.tab=secret?'vault':'notes';state.view='list';state.query='';render();document.getElementById('toast').hidden=true;}
function openSettings(){const dialog=document.getElementById('settings-dialog');const s=state.settings;
 dialog.innerHTML=`<header class="appearance-titlebar"><h2 id="settings-title">设置</h2><button class="icon-btn" data-close aria-label="关闭设置">${icon('x')}</button></header><form id="settings-form"><div class="settings-body"><div class="field"><label for="setting-shortcut">呼出 / 收起快捷键</label><input id="setting-shortcut" value="${esc(s.shortcut)}" placeholder="Alt+Q 或 F8" maxlength="60"><p>支持组合键，也可以用 F8 这样的单键。</p></div><label class="settings-row" for="setting-top">窗口始终置顶<input type="checkbox" id="setting-top" ${s.alwaysOnTop?'checked':''}></label><label class="settings-row" for="setting-start">开机启动（安装版）<input type="checkbox" id="setting-start" ${s.autoStart?'checked':''}></label><label class="settings-row" for="setting-timeout">闲置后锁定密码库<select id="setting-timeout">${[1,5,10,15,30].map(n=>`<option value="${n}" ${s.autoLockMinutes===n?'selected':''}>${n} 分钟</option>`).join('')}</select></label><p>收起窗口、电脑锁屏或休眠时，也会锁定密码库。</p><div class="settings-divider"><h3>资料与备份</h3><p>备忘录以明文保存；账号密码单独加密。备份中的密码库仍需原主密码解锁。</p><div class="settings-actions"><button type="button" class="secondary" data-setting="export">导出备份</button><button type="button" class="secondary" data-setting="import">恢复备份</button><button type="button" class="text-btn" data-setting="directory">打开数据目录</button></div></div><div class="settings-actions"><button type="button" class="secondary" data-setting="password" ${!state.vault.unlocked?'disabled':''}>修改主密码</button></div>${!state.vault.unlocked?'<p>解锁密码库后可修改主密码。</p>':''}<div class="settings-divider"><h3>版本与更新</h3><p class="settings-version">超强大脑 ${esc(state.version)}</p><div class="settings-actions"><button type="button" class="secondary" data-setting="update">检查更新</button><button type="button" class="text-btn" data-setting="repository">GitHub 仓库</button><button type="button" class="text-btn" data-setting="quit">退出软件</button></div><p id="update-status" role="status"></p><button type="button" class="secondary" data-setting="download" hidden>前往下载新版本</button></div><p id="settings-error" class="settings-error" role="alert"></p></div><footer class="settings-bottom"><button type="button" class="secondary" data-close>取消</button><button type="submit" class="primary">保存设置</button></footer></form>`;
 dialog.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>dialog.close());
 dialog.querySelector('form').onsubmit=async event=>{event.preventDefault();const error=document.getElementById('settings-error');const button=event.submitter;button.disabled=true;try{const next={...state.settings,shortcut:document.getElementById('setting-shortcut').value.trim(),alwaysOnTop:document.getElementById('setting-top').checked,autoStart:document.getElementById('setting-start').checked,autoLockMinutes:Number(document.getElementById('setting-timeout').value)};state.settings=await api.saveSettings(next);window.appearance.update(state.settings);dialog.close();render();}catch(e){error.textContent=e.message;}finally{button.disabled=false;}};
 dialog.querySelectorAll('[data-setting]').forEach(button=>button.onclick=async()=>{const command=button.dataset.setting;button.disabled=true;try{if(command==='directory')await api.openDataDirectory();else if(command==='repository')await api.openRepository();else if(command==='download')await api.openUpdate();else if(command==='export'){await flushAll();const result=await api.exportBackup();if(!result.cancelled)notify('备份已导出');}else if(command==='import'){await flushAll();const result=await api.importBackup();if(!result.cancelled){assignState(result.state);window.appearance.update(state.settings);dialog.close();render();notify('已恢复备份');}}else if(command==='password'){openPasswordChange();}else if(command==='quit'){await hideWindow(true);}else if(command==='update'){document.getElementById('update-status').textContent='正在检查…';const result=await api.checkUpdate();document.getElementById('update-status').textContent=result.message;dialog.querySelector('[data-setting="download"]').hidden=!result.available;}}catch(e){document.getElementById('settings-error').textContent=e.message;}finally{button.disabled=false;}});
 dialog.showModal();
}
function openPasswordChange(){const dialog=document.getElementById('password-dialog');dialog.innerHTML=`<header class="appearance-titlebar"><h2 id="password-dialog-title">修改主密码</h2><button class="icon-btn" data-close aria-label="关闭修改主密码">${icon('x')}</button></header><form><div class="settings-body"><div class="field"><label for="old-master">当前主密码</label><input id="old-master" type="password" autocomplete="current-password" required maxlength="1024"></div><div class="field"><label for="new-master">新主密码（至少 12 个字符）</label><input id="new-master" type="password" autocomplete="new-password" required minlength="12" maxlength="1024"></div><div class="field"><label for="repeat-master">再次输入新主密码</label><input id="repeat-master" type="password" autocomplete="new-password" required maxlength="1024"></div><p>修改后，已有的旧备份仍使用旧主密码。</p><p class="form-error" role="alert"></p></div><footer class="settings-bottom"><button class="primary" type="submit">修改主密码</button></footer></form>`;const close=()=>{dialog.close();dialog.replaceChildren();};dialog.querySelector('[data-close]').onclick=close;dialog.addEventListener('cancel',()=>dialog.replaceChildren(),{once:true});dialog.querySelector('form').onsubmit=async event=>{event.preventDefault();const form=event.target;const error=form.querySelector('.form-error');const old=document.getElementById('old-master').value,next=document.getElementById('new-master').value;if(next!==document.getElementById('repeat-master').value){error.textContent='两次输入的新主密码不一致';return;}event.submitter.disabled=true;try{await flush();await api.changePassword(old,next);form.reset();close();notify('主密码已修改');}catch(e){if(form.isConnected){error.textContent=e.message;event.submitter.disabled=false;}}};dialog.showModal();}
function assignState(data){state.notes=data.notes;state.settings=data.settings;state.vault=data.vault;state.version=data.version;state.accounts=[];state.tab='notes';state.view='list';state.id=null;state.query='';state.save='saved';}
api.onLocked(()=>{state.vault.unlocked=false;state.accounts=[];lastDeleted=null;for(const [key,job]of pending)if(job.secret)pending.delete(key);const dialog=document.getElementById('password-dialog');dialog.close();dialog.replaceChildren();document.getElementById('toast').hidden=true;if(state.tab==='vault'){state.view='list';state.id=null;state.query='';state.save='saved';render();}});
api.onPrepareHide(()=>hideWindow());api.onPrepareQuit(()=>hideWindow(true));api.onNotice(notify);
api.onShown(async()=>{try{const data=await api.state();state.vault=data.vault;if(state.tab==='vault'&&!data.vault.unlocked){state.view='list';state.id=null;state.accounts=[];render();}document.getElementById('search')?.focus();}catch(e){showError(e);}});
document.addEventListener('keydown',event=>{if(event.isComposing||event.keyCode===229)return;if(document.querySelector('dialog[open]'))return;if(event.key==='Escape'){event.preventDefault();(state.view==='edit'?action('back'):hideWindow()).catch(showError);}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();flush().catch(showError);}});
function activity(){if(Date.now()-activityAt>10000){activityAt=Date.now();api.activity().catch(()=>{});}}
document.addEventListener('keydown',activity);document.addEventListener('pointerdown',activity);document.addEventListener('input',activity);
(async()=>{try{const data=await api.state();assignState(data);window.initAppearance(state.settings,saved=>{state.settings=saved;});render();if(!data.shortcutActive)notify('快捷键被其他程序占用，可在设置中更换');}catch(error){stage.innerHTML=`<div class="startup"><h1>暂时无法打开</h1><p>${esc(error.message)}</p><p>请退出后重试，已有资料不会被覆盖。</p></div>`;}})();
